// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyTimeManager.Repository;

#nullable disable

namespace StudyTimeManager.WPF.UI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220912000327_DatabaseCreation")]
    partial class DatabaseCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2");

            modelBuilder.Entity("StudyTimeManager.Domain.Models.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ModuleId");

                    b.Property<int>("ClassHoursPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfCredits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredWeeklySelfStudyHours")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("StudyTimeManager.Domain.Models.ModuleSemesterWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ModuleSemesterWeekId");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemainingSelfStudyHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleSemesterWeeks");
                });

            modelBuilder.Entity("StudyTimeManager.Domain.Models.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("SemesterId");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("StudyTimeManager.Domain.Models.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("StudySessionId");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HoursSpent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModuleSemesterWeekId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleSemesterWeekId");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("StudyTimeManager.Domain.Models.Module", b =>
                {
                    b.HasOne("StudyTimeManager.Domain.Models.Semester", "Semester")
                        .WithMany("Modules")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("StudyTimeManager.Domain.Models.ModuleSemesterWeek", b =>
                {
                    b.HasOne("StudyTimeManager.Domain.Models.Module", "Module")
                        .WithMany("Weeks")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("StudyTimeManager.Domain.Models.StudySession", b =>
                {
                    b.HasOne("StudyTimeManager.Domain.Models.ModuleSemesterWeek", "ModuleSemesterWeek")
                        .WithMany("StudySessions")
                        .HasForeignKey("ModuleSemesterWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleSemesterWeek");
                });

            modelBuilder.Entity("StudyTimeManager.Domain.Models.Module", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("StudyTimeManager.Domain.Models.ModuleSemesterWeek", b =>
                {
                    b.Navigation("StudySessions");
                });

            modelBuilder.Entity("StudyTimeManager.Domain.Models.Semester", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
